### ISSUE TITLE
System.Net.WebException: 'The request was aborted: Could not create SSL/TLS secure channel.'

### ISSUE THREAD

**Issue by reyurquiza** [eviabs/downtify-premium#12]
System.Net.WebException
  HResult=0x80131509
  Message=The request was aborted: Could not create SSL/TLS secure channel.
  Source=System
  StackTrace:
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at SpotifyWebApi.Auth.ClientCredentials.GetToken(AuthParameters parameters)
   at Downtify.SpotifyWeb.GetISpotifyWebApiToken()

  This exception was originally thrown at this call stack:
    [External Code]
    Downtify.SpotifyWeb.GetISpotifyWebApiToken() in SpotifyDownloader.cs
    Downtify.SpotifyWeb.Auth() in SpotifyDownloader.cs
    Downtify.SpotifyDownloader.LoggedIn(SpotifySharp.SpotifySession, SpotifySharp.SpotifyError) in SpotifyDownloader.cs

Was working fine a few days ago, still kind of new to this, so forgive me if its something on my end.

**Comment by eviabs** [comment]
I updated the SpotifyWeb library, check if it solves your problem.
