### ISSUE TITLE
ohLibSpotify Error during compilation.

### ISSUE THREAD

**Issue by aarontanx** [eviabs/downtify-premium#20]
Hi, I got the following error during compilation. Is there any dependencies that I am missing?
`System.BadImageFormatException: 'Could not load file or assembly 'ohLibSpotify, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.'`

**Comment by luismiaresse** [comment]
Same here, I have the .dll but says that.

**Comment by luismiaresse** [comment]
I figured it out, you need to change arch to x86.
