### ISSUE TITLE
Please select the song you want to download

### ISSUE THREAD

**Issue by zAbzAki** [eviabs/downtify-premium#24]
I'm basically new to this thing, I think I followed the instructions right but I'm getting this error "Please select the songs you want to download" but there is no songs to select.

When I copy/paste the track on the text box, same thing happens. Please help

![image](https://user-images.githubusercontent.com/76246866/102686744-aa510d00-41fa-11eb-9fc2-f23173e6cd3c.png)

**Comment by eviabs** [comment]
1) Paste in the text box the song(s) you want to download 
2) Press `Enter` key to list the song(s) you have just pasted
3) Select the song(s) you want to download from that list
4) Press `Download`

**Comment by zAbzAki** [comment]
> 1. Paste in the text box the song(s) you want to download
> 2. Press `Enter` key to list the song(s) you have just pasted
> 3. Select the song(s) you want to download from that list
> 4. Press `Download`

Yay, got it. Thanks.
