### ISSUE TITLE
[Request] Feature: Disable Normalize

### ISSUE THREAD

**Issue by bascurtiz** [eviabs/downtify-premium#8]
Though my Spotify desktop app settings are disabled Volume-wise (like Normalize and stuff), Downtify records them Normalized.

Example, u can see it here:
![image](https://user-images.githubusercontent.com/34075088/57026411-0b009000-6c3a-11e9-9655-e08c73e91f72.png)

Can you by default disable that Normalized feature?

**Comment by eviabs** [comment]
Thanks!
Added this option to the config file.
