### ISSUE TITLE
Fails to Build using msbuild.exe

### ISSUE THREAD

**Issue by omersubash** [eviabs/downtify-premium#9]
I have no programming experience. I'm compiling without visual studio in cmd so bear with me. Using this command in cmd:
`C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe Downtify.sln`

It gives 2 warnings and 1 error. First, the warnings:
> "C:\Users\user\Desktop\downtify-premium-master\Downtify.sln" (default target) (1) ->
"C:\Users\user\Desktop\downtify-premium-master\Downtify\Downtify.csproj" (default target) (2) ->
(ResolveAssemblyReferences target) ->
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3257: The primary reference "System.Net.Http, Version=4.1.1.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL" could not be resolved because it has a higher version "4.1.1.2" than exists in the current target framework. The version found in the current target framework is "4.0.0.0". [C:\Users\user\Desktop\downtify-premium-master\Downtify\Downtify.csproj]
  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly. [C:\Users\user\Desktop\downtify-premium-master\Downtify\Downtify.csproj]

Then the error:
> "C:\Users\user\Desktop\downtify-premium-master\Downtify.sln" (default target) (1) ->
"C:\Users\user\Desktop\downtify-premium-master\Downtify\Downtify.csproj" (default target) (2) ->
(CoreCompile target) ->
  SpotifyDownloader.cs(46,15): error CS0012: The type 'System.Object' is defined in an assembly that is not referenced.
 You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
 [C:\Users\user\Desktop\downtify-premium-master\Downtify\Downtify.csproj]

I try to resolve this error by adding `<Reference Include="netstandard" />` to Downtify.csproj. Now it gives me two new errors:
> "C:\Users\user\Desktop\downtify-premium-master\Downtify.sln" (default target) (1) ->
"C:\Users\user\Desktop\downtify-premium-master\Downtify\Downtify.csproj" (default target) (2) ->
(CoreCompile target) ->
  SpotifyDownloader.cs(237,31): error CS1525: Invalid expression term '.' [C:\Users\user\Desktop\downtify-premium-master\Downtify\Downtify.csproj]
  SpotifyDownloader.cs(237,32): error CS1003: Syntax error, ':' expected [C:\Users\user\Desktop\downtify-premium-master\Downtify\Downtify.csproj]

I delete the referece and try to resolve this by deleting .vs and bin folders. It eliminates the first error and gives the same two errors when adding a new reference. Can't compile simply.

**Comment by niko2206** [comment]
Compiles without issues with Visual Studio 2019 Community Edition.

**Comment by eviabs** [comment]
You can contact me, and I'll send you the complied files (the executables)
